//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DellLanguage
    {
        public DellLanguage()
        {
            this.DellOsLanguages = new HashSet<DellOsLanguage>();
            this.Locales = new HashSet<Locale>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DellOsLanguage> DellOsLanguages { get; set; }
        public virtual ICollection<Locale> Locales { get; set; }
    }
}
