//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationServiceTags = new HashSet<NotificationServiceTag>();
            this.DellOsLanguages = new HashSet<DellOsLanguage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string NotificationTypeId { get; set; }
        public string CategoryId { get; set; }
        public string SeverityId { get; set; }
        public string StatusId { get; set; }
        public string Action1Text { get; set; }
        public string Action1Uri { get; set; }
        public string Action1ActionTypeId { get; set; }
        public string Action2Text { get; set; }
        public string Action2Uri { get; set; }
        public string Action2ActionTypeId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual ActionType ActionType1 { get; set; }
        public virtual Category Category { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<NotificationServiceTag> NotificationServiceTags { get; set; }
        public virtual ICollection<DellOsLanguage> DellOsLanguages { get; set; }
    }
}
