//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationServiceTag
    {
        public int NotificationId { get; set; }
        public string ServiceTag { get; set; }
    
        public virtual Notification Notification { get; set; }
    }
}
